name: "Build Signed APK"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Build apk
        run: |
          cd android
          ./gradlew assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/objdetect.apk

      - uses: actions/upload-artifact@v3
        with:
          name: objdetect.apk
          path: ./android/app/build/outputs/apk/objdetect.apk

      - name: Clear generated signing key
        run: |
          if [ -f "$GITHUB_WORKSPACE/key.jks" ] ; then
            rm "$GITHUB_WORKSPACE/key.jks"
          fi
        shell: bash
